# Generated by Django 3.2.9 on 2021-11-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ciudad',
            field=models.CharField(max_length=30, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='user',
            name='descripcion',
            field=models.CharField(max_length=256, null=True, verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.CharField(max_length=20, null=True, verbose_name='Telefono'),
        ),
    ]
